language: objective-c
install:
- brew install --HEAD macmade/tap/xrun
- xrun setup
script:
- xrun -scheme xrun build analyze
- xrun -project Tests/TestApp/TestApp.xcodeproj -scheme TestApp build analyze test -verbose
- xrun -project Tests/TestApp/TestApp.xcodeproj -scheme TestApp build analyze test -verbose -fail-warn || if [ $? == 0 ]; then false; else true; fi    
notifications:
    slack: xs-labs:FXh1yLXNkpcVxKZhZU6icdhI
