language: objective-c
install:
- rvm get head
- gem install xcpretty
script:
- set -o pipefail && xcodebuild -project "thx.xcodeproj" -scheme "thx" build | xcpretty
notifications:
    slack: xs-labs:FXh1yLXNkpcVxKZhZU6icdhI
